name: Playwright Tests

on: [push, pull_request]

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        env:
          HOME: /root
          BASE_URL: ${{ secrets.BASE_URL }}
          HTTP_USERNAME: ${{ secrets.HTTP_USERNAME }}
          HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}
